# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: defa24b42aa2cbc6328304467683a6a428b02bba58d35efb5269a3c6dc0a238128fb6192717c5de2ca64a03afa3813664e2172ecac563c2b962230fb24860b3e

test:
  secret_key_base: 2669db74b8cf95c50c544942bf17eea0bd5f6bcb9d0b69ccf5b1cd8d8153886949205a0260c05247f1be222bf166e491c8109d7700a7ec8974de7b068fa92077

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
